# Required to run your project under the correct environment.
language: node_js

# Versions of PHP you want your project run with.
node_js:
  - 10
  - 9

# Commands to be run before your environment runs.
before_script:
  - npm install

# Commands you want to run that will verify your build.
script:
  - mocha --timeout 10000
  - ./node_modules/.bin/eslint **/*.js

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: always
